# Header Menu
menu:
  Home: /
  # Blog: /archives/ # can set archive-dir in root config to custom value
  Technologies: /categories/Technologies
  Activities: /categories/Activities
  Projects: https://github.com/HFUUOSC
  # Contact: /contact/
  About: /about/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Social
social:
  github: https://github.com/HFUUOSC
  qq: https://qm.qq.com/cgi-bin/qm/qr?k=qa9bOKC4QWRjZ8_LTtbO_2Y2TWlnlyfa

# Miscellaneous
color_scheme: turquoise   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "678830341331820544" # as a string, from https://twitter.com/settings/widgets
twitter_username: computerlab_ # twitter username without the @
default_author: Anonymous

about: 合肥学院开源社区是由合肥学院在校开源技术爱好者和 GNU/Linux 爱好者组成的开源技术社区，旨在传播开源文化，构建开源项目，分享开源精神。
qq: 1106651511
email: admin@hfuuosc.org
address_1: 合肥学院
address_2: 锦绣大道 99 号
address_3: 合肥，中国 11249
